---
- name: apt install requirements
  apt: name={{item}} state=present
  with_items:
   - virtualbox
   - vagrant
  become: yes

- name: set Vagrantfile from template
  template:
    src: Vagrantfile
    dest: ~/vagrant/{{ vagrant_box_folder }}/Vagrantfile
