---
- name: apt install zsh, git-core
  apt: name={{item}} state=present
  with_items:
   - zsh
   - git-core
  become: yes
- name: pip install pexpect
  pip:
    name: pexpect
  become: yes
- name: download zsh master tools
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/zsh_tools.sh
- name: install zsh master tools  # todo: fix the blocking prompt
  expect:
    echo: yes
    command: sh /tmp/zsh_tools.sh
    responses:
      (.*)Do you want to change your default shell to zsh?(.*): 'y'
      (.*)asswor(.*): '{{ ansible_sudo_pass }}'
  become: yes
  become_user: '{{ remote_user }}'
- name: disable shared history
  lineinfile:
    dest: /home/{{ remote_user }}/.zshrc
    line: unsetopt share_history
    regexp: "unsetopt share_history"
    state: present
    insertafter: EOF
    create: True
