---
- name: update
  apt:
    update_cache: yes
  become: yes
- name: upgrade
  apt:
    upgrade: dist
  become: yes
- name: apt install requirements
  apt:
    name:
      - software-properties-common
      - build-essential
      - checkinstall
      - libreadline-gplv2-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
    state: present
  become: yes
- name: pip install flake8, python-dateutil
  pip:
    name:
      - flake8
      - python-dateutil
      - setuptools
      - wheel
    extra_args: --user
    executable: pip3
- name: apt repository ppa:deadsnakes/ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
    codename: bionic 
    update_cache: yes
  become: yes
- name: apt install python3.7
  apt:
    name: python3.7
  become: yes
- name: install pip3.7
  command: /usr/bin/python3.7 -m pip install pip
