---
- name: update
  apt:
    update_cache: yes
  become: yes
- name: upgrade
  apt:
    upgrade: dist
  become: yes
- name: apt install requirements
  apt: name={{item}} state=present
  with_items:
   - software-properties-common
   - build-essential
   - checkinstall
   - libreadline-gplv2-dev
   - libncursesw5-dev
   - libssl-dev
   - libsqlite3-dev
   - tk-dev
   - libgdbm-dev
   - libc6-dev
   - libbz2-dev
  become: yes
- name: apt repository ppa:deadsnakes/ppa
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
    codename: bionic 
    update_cache: yes
  become: yes
- name: apt install python3.7
  apt:
    name: python3.7
  become: yes
