---
- name: apt install terminator
  apt:
    name: terminator
  become: yes
- name: make config dir
  file:
    path: /home/{{ remote_user }}/.config/terminator/
    state: directory
- name: set config
  template:
    src: config
    dest: /home/{{ remote_user }}/.config/terminator/
