#https://websiteforstudents.com/installing-virtualbox-5-2-ubuntu-17-04-17-10/
---
- name: register kernel release
  command: uname -r
  register: kernel_release
- name: apt install gcc, make, linux-headers, dkms
  apt: name={{item}}
  with_items:
    - gcc
    - make
    - linux-headers-{{ kernel_release.stdout }}
    - dkms
  become: yes
- name: apt key oracle_vbox_2016
  apt_key:
    url: https://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
    state: present
  become: yes
- name: apt key oracle_vbox
  apt_key:
    url: https://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
    state: present
  become: yes
- name: apt repository https://download.virtualbox.org/virtualbox/debian
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian xenial contrib
    state: present
    update_cache: yes
  become: yes
- name: apt install virtualbox
  apt:
    name: virtualbox
  become: yes
