---
- name: update
  apt:
    update_cache: yes
  become: yes
- name: upgrade
  apt:
    upgrade: dist
  become: yes
- name: apt key https://www.postgresql.org/media/keys/ACCC4CF8.asc
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes
- name: ensure postgres apt repository exists
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main' update_cache=yes
  become: yes
- name: apt install postgresql
  apt:
    name: postgresql-11
  become: yes
- name: pip install psycopg2
  pip:
    name: psycopg2-binary
  become: yes
- name: activate service
  service:
    name: postgresql
    state: started
  become: yes
- name: create user
  postgresql_user:
    name: '{{ postgres_user.name }}'
    password: '{{ postgres_user.pass | default(omit) }}'
    encrypted: yes
    state: present
    login_user: postgres
    role_attr_flags: SUPERUSER,CREATEROLE,CREATEDB,LOGIN,REPLICATION,BYPASSRLS
  become: yes
  become_user: postgres
- name: assign privs
  postgresql_privs:
    roles: '{{ postgres_user.name }}'
    database: postgres
    privs: ALL
    grant_option: true
    login: postgres
    objs: ALL_IN_SCHEMA
  become: yes
  become_user: postgres
- name: add PGDATABASE env var
  lineinfile:
    dest: '{{ profile_file_path }}'
    line: export PGDATABASE=postgres
    regexp: ^export PGDATABASE\=postgres$
    state: present
    insertafter: EOF
    create: True
